server {
    listen 80;
    location / {
        if ($args ~ "^(.*)query=(.*)$") {
            set $args $1update=$2;
        }
        proxy_set_header Accept application/json;
        proxy_pass http://meta-write:3030;
    }
}
